spring.application.name=CourseManagementSystem
server.port=8080

# Database
spring.datasource.url=jdbc:postgresql://localhost:5432/coursems
spring.datasource.username=postgres
spring.datasource.password=123456

# JPA
spring.jpa.hibernate.ddl-auto=none
spring.jpa.generate-ddl=false
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# Prevent Spring SQL init scripts from running automatically
spring.sql.init.mode=never

# JWT
jwt.secret=MySuperLongSecretKeyForCourseManagementSystem2026AtLeast64CharactersLong!!!
jwt.expiration=86400000

logging.level.org.hibernate.SQL=DEBUG